### ISSUE TITLE
Incorrect Poly6 gradient

### ISSUE THREAD

**Issue by Wumpf** [rustsim/salva#2]
I think the implementation of the Poly6 gradient has a bug:
https://github.com/rustsim/salva/blob/master/src/kernel/poly6_kernel.rs#L34
The is second multiplication with r which is incorrect, to my understanding it should be `normalizer * (h * h - r * r).powi(2) * na::convert(-6.0)`

Derivative of the original function (used 2d normalizer here)
https://www.wolframalpha.com/input/?i=%284%2F%28pi+*+h%5E8%29+*+%28h%5E2+-+x%5E2%29%5E3%29+d%2Fdx
(for the "gradient factor" just taking the derivative is enough, but for completeness here's a proper gradient :) https://www.wolframalpha.com/input/?i=grad+%284%2F%28pi+*+h%5E8%29+*+%28h%5E2+-+sqrt%28x%5E2+%2B+y%5E2%29%5E2%29%5E3%29)

**Comment by sebcrozet** [comment]
Hi! I'm not sure if I'm missing something, but, the derivative given by wolframalpha does contain this second multiplication by `r` (which is `x`in the following image):

![image](https://user-images.githubusercontent.com/1734958/72470791-ba3dc100-37e1-11ea-8fa5-14efe656fc2e.png)

**Comment by Wumpf** [comment]
Oh darn I somehow overlooked it 😕 . Sorry and thanks for checking on it!

**Comment by Wumpf** [comment]
Ah! My confusion stemmed from how Salva multiplies with the **norm** of the direction afterwards (which potentially sacrifies a bit performance) for a more unified framework. If `scalar_apply_diff` _would_ be multiplied with the original vector _then_ yes there would be a factor r too many.
Still learning 😄
