### ISSUE TITLE
Update to latest rapier/nalgebra versions

### ISSUE THREAD

**Issue by NiklasRiewald** [rustsim/salva#22]

**Comment by NiklasRiewald** [comment]
If there is nobody else working on this, I'll try to provide a pull request

**Comment by rezural** [comment]
@NiklasRiewald, I didnt notice this issue when I looked at upgrading salva, anyway I have submitted a WIP PR #23 , which makes most of the manual changes needed to compile.

There is still the graphics code which needs to be updated (and perhaps rapier needs to be updated as well, I think seb just disabled plugin graphics related code.) If you feel like working on this, please do so.

Hopefully you havent done too much on this...

**Comment by NiklasRiewald** [comment]
thanks for updating!
